[package]
name = "pointing-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
scan_fmt = "0.2.6"
uom = "0.35.0"
